//! Runtime/session-level compaction controller.

use super::refs::BlockRef;
use super::{
    CompactSummaryBackend, CompactSummaryError, CompactSummaryRequest, CompactionEngine,
    CompactionPhase, CompactionPolicy, CompactionReason, LocalLlmSummary, SummaryPart, auto_select,
    count_tokens_cached,
};
use crate::agent::memory::{AgentMemory, AgentMessage};
use crate::config::{AGENT_RESPONSE_SOFT_MAX_OUTPUT_TOKENS, ModelInfo};
use crate::llm::{LlmClient, ToolDefinition};
use std::sync::Arc;
use std::time::Duration;
use thiserror::Error;

/// Controller-level compaction failure.
#[derive(Debug, Error)]
pub enum CompactionControllerError {
    /// Summary generation failed.
    #[error(transparent)]
    Summary(#[from] CompactSummaryError),
    /// Engine rejected the compression selection.
    #[error(transparent)]
    Engine(#[from] super::CompactionError),
}

// ---------------------------------------------------------------------------
// Engine-based compaction (new unified path)
// ---------------------------------------------------------------------------

/// Result of a successful engine-based compaction pass.
#[derive(Debug, Clone)]
pub struct EngineCompactionOutcome {
    /// Block ref allocated by the engine.
    pub block_ref: BlockRef,
    /// Summary text generated by the LLM backend.
    pub summary_text: String,
    /// Provider that generated the summary.
    pub provider: String,
    /// Model route used for summary generation.
    pub route: String,
    /// Why compaction was requested.
    pub reason: CompactionReason,
    /// Runtime phase where compaction happened.
    pub phase: CompactionPhase,
    /// Rendered token count before compaction.
    pub token_before: usize,
    /// Rendered token count after compaction.
    pub token_after: usize,
    /// Rendered item count before compaction.
    pub history_items_before: usize,
    /// Rendered item count after compaction.
    pub history_items_after: usize,
}

/// Result when compaction was skipped (nothing to compress).
#[derive(Debug, Clone)]
pub struct EngineCompactionSkipped {
    /// Why compaction was requested.
    pub reason: CompactionReason,
    /// Runtime phase where compaction was attempted.
    pub phase: CompactionPhase,
    /// Human-readable reason for the skip.
    pub skipped_reason: String,
}

/// Outcome of `compact_via_engine`.
#[derive(Debug, Clone)]
pub enum EngineCompactionResult {
    /// A new block was created.
    Applied(EngineCompactionOutcome),
    /// No compressible range was found.
    Skipped(EngineCompactionSkipped),
}

/// Single entrypoint for runtime/session-level compaction.
pub struct CompactionController {
    summary_backend: Arc<dyn CompactSummaryBackend>,
}

impl CompactionController {
    /// Create a controller with one provider-agnostic summary backend.
    #[must_use]
    pub fn new(summary_backend: Arc<dyn CompactSummaryBackend>) -> Self {
        Self { summary_backend }
    }

    /// Create the default provider-agnostic local LLM compaction controller.
    #[must_use]
    pub fn local_llm(llm_client: Arc<LlmClient>, timeout_secs: u64) -> Self {
        Self::new(Arc::new(LocalLlmSummary::new(
            llm_client,
            Duration::from_secs(timeout_secs.max(1)),
        )))
    }

    /// Run engine-based automatic compaction.
    ///
    /// This is the unified path for all automatic triggers (pre-sampling,
    /// context-limit, model-downshift, hook/manual). It selects a compressible
    /// range, generates an LLM summary, and applies through `CompactionEngine`,
    /// creating a block in `CompactionState` without destroying raw memory.
    ///
    /// When `force` is `false`, the budget threshold is checked first — if the
    /// rendered context is within budget, compaction is skipped.
    pub async fn compact_via_engine(
        &self,
        memory: &mut AgentMemory,
        route: &ModelInfo,
        task: &str,
        tools: &[ToolDefinition],
        system_prompt: &str,
        reason: CompactionReason,
        phase: CompactionPhase,
        force: bool,
    ) -> Result<EngineCompactionResult, CompactionControllerError> {
        let policy = CompactionPolicy::default();
        let context_window = if route.context_window_tokens == 0 {
            memory.max_tokens()
        } else {
            route.context_window_tokens as usize
        };

        // Budget threshold check (skip if not forced and within budget).
        if !force {
            let system_prompt_tokens = count_tokens_cached(system_prompt);
            let tool_tokens = tool_schema_tokens(tools);
            let hot_memory_tokens = memory.token_count();
            let projected_total = system_prompt_tokens
                .saturating_add(tool_tokens)
                .saturating_add(hot_memory_tokens)
                .saturating_add(policy.hard_reserve_tokens);
            let compact_threshold =
                context_window.saturating_mul(policy.compact_threshold_percent as usize) / 100;
            let over_limit_threshold =
                context_window.saturating_mul(policy.over_limit_threshold_percent as usize) / 100;

            if projected_total < compact_threshold && projected_total < over_limit_threshold {
                return Ok(EngineCompactionResult::Skipped(EngineCompactionSkipped {
                    reason,
                    phase,
                    skipped_reason: "Context is within budget threshold".to_string(),
                }));
            }
        }

        // Compute target token budget for the recent tail.
        let system_prompt_tokens = count_tokens_cached(system_prompt);
        let tool_tokens = tool_schema_tokens(tools);
        let target_tokens = auto_select::target_history_tokens(
            context_window,
            system_prompt_tokens,
            tool_tokens,
            &policy,
        );

        // Select the compressible range.
        let selection = match auto_select::select_automatic_compression_range(
            memory.get_messages(),
            memory.compaction_state(),
            target_tokens,
        ) {
            Some(selection) => selection,
            None => {
                return Ok(EngineCompactionResult::Skipped(EngineCompactionSkipped {
                    reason,
                    phase,
                    skipped_reason: "No compressible range available".to_string(),
                }));
            }
        };

        // Record rendered token/item counts before compaction.
        let token_before = memory.rendered_token_count();
        let history_items_before = memory.rendered_item_count();

        // Select bounded source messages for the summary LLM prompt.
        let source_messages = memory.get_messages().to_vec();
        let previous_summary = memory.compaction_state().previous_block_summary_text();
        let summary_source_messages = bounded_summary_source_messages(&source_messages, route);

        // Generate the summary via the LLM backend.
        let summary_result = self
            .summary_backend
            .summarize(CompactSummaryRequest {
                task,
                route,
                messages: &summary_source_messages,
                previous_summary: previous_summary.as_deref(),
            })
            .await?;

        // Apply through the engine — creates a block, consumes old blocks.
        let source_messages_for_engine = memory.get_messages().to_vec();
        let block_ref = CompactionEngine::apply_compression(
            memory.compaction_state_mut(),
            &source_messages_for_engine,
            &selection,
            vec![SummaryPart::Text(summary_result.summary_text.clone())],
        )?;

        // Record rendered token/item counts after compaction.
        let token_after = memory.rendered_token_count();
        let history_items_after = memory.rendered_item_count();

        Ok(EngineCompactionResult::Applied(EngineCompactionOutcome {
            block_ref,
            summary_text: summary_result.summary_text,
            provider: summary_result.provider,
            route: summary_result.route,
            reason,
            phase,
            token_before,
            token_after,
            history_items_before,
            history_items_after,
        }))
    }
}

fn bounded_summary_source_messages(
    source_messages: &[AgentMessage],
    route: &ModelInfo,
) -> Vec<AgentMessage> {
    use crate::agent::compaction::CompactionRetention;

    let route_window = (route.context_window_tokens as usize).max(8_000);
    let output_budget = (route
        .max_output_tokens
        .min(AGENT_RESPONSE_SOFT_MAX_OUTPUT_TOKENS) as usize)
        .max(512);
    let source_budget = route_window
        .saturating_sub(output_budget)
        .saturating_sub(2_000)
        .clamp(4_000, 180_000);

    let mut selected_indices = std::collections::BTreeSet::new();
    let mut used_tokens = 0usize;

    for (index, message) in source_messages.iter().enumerate() {
        if matches!(
            message.retention(),
            CompactionRetention::Pinned | CompactionRetention::ProtectedLive
        ) {
            selected_indices.insert(index);
            used_tokens = used_tokens.saturating_add(message_summary_tokens(message));
        }
    }

    for (index, message) in source_messages.iter().enumerate().rev() {
        if selected_indices.contains(&index) {
            continue;
        }
        let message_tokens = message_summary_tokens(message);
        if used_tokens.saturating_add(message_tokens) > source_budget
            && !selected_indices.is_empty()
        {
            continue;
        }
        selected_indices.insert(index);
        used_tokens = used_tokens.saturating_add(message_tokens);
        if used_tokens >= source_budget {
            break;
        }
    }

    selected_indices
        .into_iter()
        .filter_map(|index| source_messages.get(index).cloned())
        .collect()
}

fn message_summary_tokens(message: &AgentMessage) -> usize {
    crate::agent::compaction::count_tokens_cached(&message.content).saturating_add(
        message
            .reasoning
            .as_deref()
            .map(crate::agent::compaction::count_tokens_cached)
            .unwrap_or(0),
    )
}

/// Estimate the token cost of serialized tool schemas.
fn tool_schema_tokens(tools: &[ToolDefinition]) -> usize {
    tools.iter().fold(0usize, |acc, tool| {
        let parameter_tokens = serde_json::to_string(&tool.parameters)
            .ok()
            .map_or(0, |params| count_tokens_cached(&params));
        acc.saturating_add(count_tokens_cached(&tool.name))
            .saturating_add(count_tokens_cached(&tool.description))
            .saturating_add(parameter_tokens)
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agent::compaction::CompactSummaryResult;
    use async_trait::async_trait;

    struct StaticSummaryBackend;

    #[async_trait]
    impl CompactSummaryBackend for StaticSummaryBackend {
        async fn summarize(
            &self,
            request: CompactSummaryRequest<'_>,
        ) -> Result<CompactSummaryResult, CompactSummaryError> {
            Ok(CompactSummaryResult {
                summary_text: "Current state and remaining work.".to_string(),
                provider: request.route.provider.clone(),
                route: request.route.id.clone(),
            })
        }
    }

    #[test]
    fn summary_source_is_bounded_but_keeps_pinned_context_and_recent_tail() {
        let route = ModelInfo {
            id: "agent-model".to_string(),
            provider: "mock".to_string(),
            max_output_tokens: 512,
            context_window_tokens: 8_000,
            weight: 1,
        };
        let mut messages = vec![
            AgentMessage::topic_agents_md("# Topic AGENTS\nKeep this instruction."),
            AgentMessage::user_task("Finish the compaction cleanup."),
        ];
        for index in 0..30 {
            messages.push(AgentMessage::user_turn(format!(
                "old-{index}: {}",
                "large historical context ".repeat(120)
            )));
        }
        messages.push(AgentMessage::assistant("recent important finding"));

        let selected = bounded_summary_source_messages(&messages, &route);
        let selected_content = selected
            .iter()
            .map(|message| message.content.as_str())
            .collect::<Vec<_>>()
            .join("\n");

        assert!(selected_content.contains("Keep this instruction."));
        assert!(selected_content.contains("Finish the compaction cleanup."));
        assert!(selected_content.contains("recent important finding"));
        assert!(!selected_content.contains("old-0:"));
    }
}
