//! Runtime/session-level compaction controller.

use super::refs::BlockRef;
use super::{
    CompactSummaryBackend, CompactSummaryError, CompactSummaryRequest, CompactionEngine,
    CompactionPhase, CompactionPolicy, CompactionReason, LocalLlmSummary, SummaryPart, auto_select,
    count_tokens_cached,
};
use crate::agent::memory::{AgentMemory, AgentMessage};
use crate::config::{AGENT_RESPONSE_SOFT_MAX_OUTPUT_TOKENS, ModelInfo};
use crate::llm::{LlmClient, ToolDefinition};
use std::collections::BTreeSet;
use std::sync::Arc;
use std::time::Duration;
use thiserror::Error;

/// Controller-level compaction failure.
#[derive(Debug, Error)]
pub enum CompactionControllerError {
    /// Summary generation failed.
    #[error(transparent)]
    Summary(#[from] CompactSummaryError),
    /// Engine rejected the compression selection.
    #[error(transparent)]
    Engine(#[from] super::CompactionError),
}

// ---------------------------------------------------------------------------
// Engine-based compaction (new unified path)
// ---------------------------------------------------------------------------

/// Result of a successful engine-based compaction pass.
#[derive(Debug, Clone)]
pub struct EngineCompactionOutcome {
    /// Block ref allocated by the engine.
    pub block_ref: BlockRef,
    /// Summary text generated by the LLM backend.
    pub summary_text: String,
    /// Provider that generated the summary.
    pub provider: String,
    /// Model route used for summary generation.
    pub route: String,
    /// Why compaction was requested.
    pub reason: CompactionReason,
    /// Runtime phase where compaction happened.
    pub phase: CompactionPhase,
    /// Rendered token count before compaction.
    pub token_before: usize,
    /// Rendered token count after compaction.
    pub token_after: usize,
    /// Rendered item count before compaction.
    pub history_items_before: usize,
    /// Rendered item count after compaction.
    pub history_items_after: usize,
}

/// Result when compaction was skipped (nothing to compress).
#[derive(Debug, Clone)]
pub struct EngineCompactionSkipped {
    /// Why compaction was requested.
    pub reason: CompactionReason,
    /// Runtime phase where compaction was attempted.
    pub phase: CompactionPhase,
    /// Human-readable reason for the skip.
    pub skipped_reason: String,
}

/// Outcome of `compact_via_engine`.
#[derive(Debug, Clone)]
pub enum EngineCompactionResult {
    /// A new block was created.
    Applied(EngineCompactionOutcome),
    /// No compressible range was found.
    Skipped(EngineCompactionSkipped),
}

/// Single entrypoint for runtime/session-level compaction.
pub struct CompactionController {
    summary_backend: Arc<dyn CompactSummaryBackend>,
}

impl CompactionController {
    /// Create a controller with one provider-agnostic summary backend.
    #[must_use]
    pub fn new(summary_backend: Arc<dyn CompactSummaryBackend>) -> Self {
        Self { summary_backend }
    }

    /// Create the default provider-agnostic local LLM compaction controller.
    #[must_use]
    pub fn local_llm(llm_client: Arc<LlmClient>, timeout_secs: u64) -> Self {
        Self::new(Arc::new(LocalLlmSummary::new(
            llm_client,
            Duration::from_secs(timeout_secs.max(1)),
        )))
    }

    /// Run engine-based automatic compaction.
    ///
    /// This is the unified path for all automatic triggers (pre-sampling,
    /// context-limit, model-downshift, hook/manual). It selects a compressible
    /// range, generates an LLM summary, and applies through `CompactionEngine`,
    /// creating a block in `CompactionState` without destroying raw memory.
    ///
    /// When `force` is `false`, the budget threshold is checked first — if the
    /// rendered context is within budget, compaction is skipped.
    pub async fn compact_via_engine(
        &self,
        memory: &mut AgentMemory,
        route: &ModelInfo,
        task: &str,
        tools: &[ToolDefinition],
        system_prompt: &str,
        reason: CompactionReason,
        phase: CompactionPhase,
        force: bool,
    ) -> Result<EngineCompactionResult, CompactionControllerError> {
        let policy = CompactionPolicy::default();
        let context_window = if route.context_window_tokens == 0 {
            memory.max_tokens()
        } else {
            route.context_window_tokens as usize
        };

        // Budget threshold check (skip if not forced and within budget).
        if !force {
            let system_prompt_tokens = count_tokens_cached(system_prompt);
            let tool_tokens = tool_schema_tokens(tools);
            let hot_memory_tokens = memory.rendered_token_count();
            let projected_total = system_prompt_tokens
                .saturating_add(tool_tokens)
                .saturating_add(hot_memory_tokens)
                .saturating_add(policy.hard_reserve_tokens);
            let compact_threshold =
                context_window.saturating_mul(policy.compact_threshold_percent as usize) / 100;
            let over_limit_threshold =
                context_window.saturating_mul(policy.over_limit_threshold_percent as usize) / 100;

            if projected_total < compact_threshold && projected_total < over_limit_threshold {
                return Ok(EngineCompactionResult::Skipped(EngineCompactionSkipped {
                    reason,
                    phase,
                    skipped_reason: "Context is within budget threshold".to_string(),
                }));
            }
        }

        // Compute target token budget for the recent tail.
        let system_prompt_tokens = count_tokens_cached(system_prompt);
        let tool_tokens = tool_schema_tokens(tools);
        let target_tokens = auto_select::target_history_tokens(
            context_window,
            system_prompt_tokens,
            tool_tokens,
            &policy,
        );

        // Select the compressible range.
        let selection = match auto_select::select_automatic_compression_range(
            memory.get_messages(),
            memory.compaction_state(),
            target_tokens,
        ) {
            Some(selection) => selection,
            None => {
                return Ok(EngineCompactionResult::Skipped(EngineCompactionSkipped {
                    reason,
                    phase,
                    skipped_reason: "No compressible range available".to_string(),
                }));
            }
        };

        // Resolve the selected raw range once. The summary LLM sees only this
        // range; consumed active blocks are preserved structurally as BlockRef
        // parts instead of being flattened into a global previous summary.
        let source_messages = memory.get_messages().to_vec();
        let selected_indices = resolve_selection_indices(&source_messages, &selection)?;
        let consumed_block_refs =
            consumed_block_refs_for_selection(memory.compaction_state(), &selected_indices);
        let selected_summary_source_messages = selected_summary_source_messages(
            &source_messages,
            memory.compaction_state(),
            &selected_indices,
            &consumed_block_refs,
        );
        let summary_source_messages =
            bounded_summary_source_messages(&selected_summary_source_messages, route);

        // Record rendered token/item counts before compaction.
        let token_before = memory.rendered_token_count();
        let history_items_before = memory.rendered_item_count();

        // Generate the summary via the LLM backend.
        let summary_result = self
            .summary_backend
            .summarize(CompactSummaryRequest {
                task,
                route,
                messages: &summary_source_messages,
                previous_summary: None,
            })
            .await?;

        // Apply through a cloned state first. A compaction block is committed
        // only if it actually reduces the rendered model-facing context.
        let source_messages_for_engine = memory.get_messages().to_vec();
        let mut summary_parts = vec![SummaryPart::Text(summary_result.summary_text.clone())];
        summary_parts.extend(
            consumed_block_refs
                .iter()
                .copied()
                .map(SummaryPart::BlockRef),
        );
        let mut candidate_state = memory.compaction_state().clone();
        CompactionEngine::apply_compression(
            &mut candidate_state,
            &source_messages_for_engine,
            &selection,
            summary_parts.clone(),
        )?;
        let candidate_token_after =
            rendered_token_count_for_state(&source_messages_for_engine, &candidate_state);
        let candidate_history_items_after =
            rendered_item_count_for_state(&source_messages_for_engine, &candidate_state);
        if candidate_token_after >= token_before {
            return Ok(EngineCompactionResult::Skipped(EngineCompactionSkipped {
                reason,
                phase,
                skipped_reason: format!(
                    "Compaction would not reduce rendered context ({token_before} -> {candidate_token_after})"
                ),
            }));
        }

        // Apply through the engine — creates a block, consumes old blocks.
        let block_ref = CompactionEngine::apply_compression(
            memory.compaction_state_mut(),
            &source_messages_for_engine,
            &selection,
            summary_parts,
        )?;

        // Record rendered token/item counts after compaction.
        let token_after = memory.rendered_token_count();
        let history_items_after = candidate_history_items_after;

        Ok(EngineCompactionResult::Applied(EngineCompactionOutcome {
            block_ref,
            summary_text: summary_result.summary_text,
            provider: summary_result.provider,
            route: summary_result.route,
            reason,
            phase,
            token_before,
            token_after,
            history_items_before,
            history_items_after,
        }))
    }
}

fn rendered_token_count_for_state(
    messages: &[AgentMessage],
    state: &super::CompactionState,
) -> usize {
    super::CompactionRenderer::render(messages, state, &super::RenderPolicy::default())
        .iter()
        .map(|message| {
            let mut tokens = count_tokens_cached(&message.content);
            if let Some(reasoning) = message.reasoning_content.as_deref() {
                tokens = tokens.saturating_add(count_tokens_cached(reasoning));
            }
            tokens
        })
        .sum()
}

fn rendered_item_count_for_state(
    messages: &[AgentMessage],
    state: &super::CompactionState,
) -> usize {
    super::CompactionRenderer::render(messages, state, &super::RenderPolicy::default()).len()
}

fn resolve_selection_indices(
    messages: &[AgentMessage],
    selection: &super::CompressionSelection,
) -> Result<BTreeSet<usize>, super::CompactionError> {
    let message_count = messages.len();
    match selection {
        super::CompressionSelection::Range { start, end } => {
            let start_idx = start
                .resolve(message_count)
                .ok_or(super::CompactionError::InvalidMessageRef(*start))?;
            let end_idx = end
                .resolve(message_count)
                .ok_or(super::CompactionError::InvalidMessageRef(*end))?;
            if start_idx > end_idx {
                return Err(super::CompactionError::InvalidRange {
                    start: *start,
                    end: *end,
                });
            }
            Ok((start_idx..=end_idx).collect())
        }
        super::CompressionSelection::Messages { refs } => {
            if refs.is_empty() {
                return Err(super::CompactionError::EmptySelection);
            }
            refs.iter()
                .map(|reff| {
                    reff.resolve(message_count)
                        .ok_or(super::CompactionError::InvalidMessageRef(*reff))
                })
                .collect()
        }
    }
}

fn consumed_block_refs_for_selection(
    state: &super::CompactionState,
    selected_indices: &BTreeSet<usize>,
) -> Vec<super::BlockRef> {
    state
        .blocks()
        .values()
        .filter(|block| block.is_active())
        .filter(|block| {
            block
                .direct_message_indices()
                .iter()
                .all(|index| selected_indices.contains(index))
        })
        .map(super::CompressionBlock::block_ref)
        .collect()
}

fn selected_summary_source_messages(
    messages: &[AgentMessage],
    state: &super::CompactionState,
    selected_indices: &BTreeSet<usize>,
    consumed_block_refs: &[super::BlockRef],
) -> Vec<AgentMessage> {
    let consumed_effective_indices: BTreeSet<usize> = consumed_block_refs
        .iter()
        .filter_map(|block_ref| state.blocks().get(block_ref))
        .flat_map(|block| block.effective_message_indices(state))
        .collect();

    selected_indices
        .iter()
        .filter(|index| !consumed_effective_indices.contains(index))
        .filter_map(|index| messages.get(*index).cloned())
        .collect()
}

fn bounded_summary_source_messages(
    source_messages: &[AgentMessage],
    route: &ModelInfo,
) -> Vec<AgentMessage> {
    use crate::agent::compaction::CompactionRetention;

    let route_window = (route.context_window_tokens as usize).max(8_000);
    let output_budget = (route
        .max_output_tokens
        .min(AGENT_RESPONSE_SOFT_MAX_OUTPUT_TOKENS) as usize)
        .max(512);
    let source_budget = route_window
        .saturating_sub(output_budget)
        .saturating_sub(2_000)
        .clamp(4_000, 180_000);

    let mut selected_indices = std::collections::BTreeSet::new();
    let mut used_tokens = 0usize;

    for (index, message) in source_messages.iter().enumerate() {
        if matches!(
            message.retention(),
            CompactionRetention::Pinned | CompactionRetention::ProtectedLive
        ) {
            selected_indices.insert(index);
            used_tokens = used_tokens.saturating_add(message_summary_tokens(message));
        }
    }

    for (index, message) in source_messages.iter().enumerate().rev() {
        if selected_indices.contains(&index) {
            continue;
        }
        let message_tokens = message_summary_tokens(message);
        if used_tokens.saturating_add(message_tokens) > source_budget
            && !selected_indices.is_empty()
        {
            continue;
        }
        selected_indices.insert(index);
        used_tokens = used_tokens.saturating_add(message_tokens);
        if used_tokens >= source_budget {
            break;
        }
    }

    selected_indices
        .into_iter()
        .filter_map(|index| source_messages.get(index).cloned())
        .collect()
}

fn message_summary_tokens(message: &AgentMessage) -> usize {
    crate::agent::compaction::count_tokens_cached(&message.content).saturating_add(
        message
            .reasoning
            .as_deref()
            .map(crate::agent::compaction::count_tokens_cached)
            .unwrap_or(0),
    )
}

/// Estimate the token cost of serialized tool schemas.
fn tool_schema_tokens(tools: &[ToolDefinition]) -> usize {
    tools.iter().fold(0usize, |acc, tool| {
        let parameter_tokens = serde_json::to_string(&tool.parameters)
            .ok()
            .map_or(0, |params| count_tokens_cached(&params));
        acc.saturating_add(count_tokens_cached(&tool.name))
            .saturating_add(count_tokens_cached(&tool.description))
            .saturating_add(parameter_tokens)
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agent::compaction::CompactSummaryResult;
    use async_trait::async_trait;
    use std::sync::{Arc, Mutex};

    #[derive(Debug, Default)]
    struct CapturedSummaryRequest {
        contents: Vec<String>,
        previous_summary: Option<String>,
    }

    struct CapturingSummaryBackend {
        summary_text: String,
        captured: Arc<Mutex<Option<CapturedSummaryRequest>>>,
    }

    #[async_trait]
    impl CompactSummaryBackend for CapturingSummaryBackend {
        async fn summarize(
            &self,
            request: CompactSummaryRequest<'_>,
        ) -> Result<CompactSummaryResult, CompactSummaryError> {
            *self.captured.lock().expect("capture lock") = Some(CapturedSummaryRequest {
                contents: request
                    .messages
                    .iter()
                    .map(|message| message.content.clone())
                    .collect(),
                previous_summary: request.previous_summary.map(str::to_string),
            });
            Ok(CompactSummaryResult {
                summary_text: self.summary_text.clone(),
                provider: request.route.provider.clone(),
                route: request.route.id.clone(),
            })
        }
    }

    fn route(context_window_tokens: u32) -> ModelInfo {
        ModelInfo {
            id: "agent-model".to_string(),
            provider: "mock".to_string(),
            max_output_tokens: 512,
            context_window_tokens,
            weight: 1,
        }
    }

    #[test]
    fn summary_source_is_bounded_but_keeps_pinned_context_and_recent_tail() {
        let route = route(8_000);
        let mut messages = vec![
            AgentMessage::topic_agents_md("# Topic AGENTS\nKeep this instruction."),
            AgentMessage::user_task("Finish the compaction cleanup."),
        ];
        for index in 0..30 {
            messages.push(AgentMessage::user_turn(format!(
                "old-{index}: {}",
                "large historical context ".repeat(120)
            )));
        }
        messages.push(AgentMessage::assistant("recent important finding"));

        let selected = bounded_summary_source_messages(&messages, &route);
        let selected_content = selected
            .iter()
            .map(|message| message.content.as_str())
            .collect::<Vec<_>>()
            .join("\n");

        assert!(selected_content.contains("Keep this instruction."));
        assert!(selected_content.contains("Finish the compaction cleanup."));
        assert!(selected_content.contains("recent important finding"));
        assert!(!selected_content.contains("old-0:"));
    }

    #[tokio::test]
    async fn compact_via_engine_summarizes_only_selected_range() {
        let captured = Arc::new(Mutex::new(None));
        let controller = CompactionController::new(Arc::new(CapturingSummaryBackend {
            summary_text: "selected old range summarized".to_string(),
            captured: Arc::clone(&captured),
        }));
        let mut memory = AgentMemory::new(20_000);
        memory.add_message(AgentMessage::user_task("Find laptops"));
        memory.add_message(AgentMessage::user(format!(
            "OLD SHOULD BE SUMMARIZED {}",
            "large ".repeat(6_000)
        )));
        memory.add_message(AgentMessage::user("RECENT MUST STAY RAW 1"));
        memory.add_message(AgentMessage::user("RECENT MUST STAY RAW 2"));
        memory.add_message(AgentMessage::user("RECENT MUST STAY RAW 3"));

        let result = controller
            .compact_via_engine(
                &mut memory,
                &route(20_000),
                "Find laptops",
                &[],
                "system prompt",
                CompactionReason::Manual,
                CompactionPhase::Manual,
                true,
            )
            .await
            .expect("compaction succeeds");

        assert!(matches!(result, EngineCompactionResult::Applied(_)));
        let captured = captured
            .lock()
            .expect("capture lock")
            .take()
            .expect("summary request captured");
        let joined = captured.contents.join("\n");
        assert!(joined.contains("OLD SHOULD BE SUMMARIZED"));
        assert!(!joined.contains("RECENT MUST STAY RAW"));
        assert_eq!(captured.previous_summary, None);
    }

    #[tokio::test]
    async fn compact_via_engine_skips_when_summary_would_not_reduce_rendered_context() {
        let captured = Arc::new(Mutex::new(None));
        let controller = CompactionController::new(Arc::new(CapturingSummaryBackend {
            summary_text: "expanded summary ".repeat(8_000),
            captured,
        }));
        let mut memory = AgentMemory::new(20_000);
        memory.add_message(AgentMessage::user_task("Find laptops"));
        memory.add_message(AgentMessage::user(format!(
            "old range {}",
            "large ".repeat(6_000)
        )));
        memory.add_message(AgentMessage::user("recent requirement 1"));
        memory.add_message(AgentMessage::user("recent requirement 2"));
        memory.add_message(AgentMessage::user("recent requirement 3"));

        let result = controller
            .compact_via_engine(
                &mut memory,
                &route(20_000),
                "Find laptops",
                &[],
                "system prompt",
                CompactionReason::Manual,
                CompactionPhase::Manual,
                true,
            )
            .await
            .expect("compaction call succeeds");

        match result {
            EngineCompactionResult::Skipped(skipped) => {
                assert!(
                    skipped
                        .skipped_reason
                        .contains("would not reduce rendered context")
                );
            }
            EngineCompactionResult::Applied(_) => panic!("no-op compaction must not be applied"),
        }
        assert!(!memory.compaction_state().has_active_blocks());
    }
}
