//! Shared types for Agent Mode context compaction.

use crate::config::AGENT_COMPACT_THRESHOLD;
use crate::llm::ToolDefinition;
use serde::{Deserialize, Serialize};

/// Stable semantic kind for an entry stored in hot agent memory.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub enum AgentMessageKind {
    /// Backward-compatible fallback for messages persisted before Stage 2.
    #[default]
    Legacy,
    /// Generic system context injected into the run.
    SystemContext,
    /// Topic-scoped pinned `AGENTS.md` content.
    TopicAgentsMd,
    /// Primary user task for the current run.
    UserTask,
    /// Additional user context injected while a run is active.
    RuntimeContext,
    /// Generic user turn without stronger typing metadata.
    UserTurn,
    /// Final or intermediate assistant answer.
    AssistantResponse,
    /// Assistant answer that contains hidden reasoning content.
    AssistantReasoning,
    /// Assistant message that requests tool execution.
    AssistantToolCall,
    /// Raw tool result retained in hot memory.
    ToolResult,
    /// Dynamically loaded skill instructions.
    SkillContext,
    /// System replay instruction after operator approval.
    ApprovalReplay,
    /// System status about topic-scoped infra / approvals.
    InfraStatus,
    /// Summary generated by compaction.
    Summary,
    /// Lightweight placeholder pointing at archived context.
    ArchiveReference,
}

/// Retention class used by future compaction policies.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum CompactionRetention {
    /// Must stay raw in hot context and never be compacted.
    Pinned,
    /// Keep raw while the work is still active.
    ProtectedLive,
    /// Large artifacts that should be pruned or externalized before summary.
    PrunableArtifact,
    /// Historical conversation content eligible for summary compaction.
    CompactableHistory,
}

impl AgentMessageKind {
    /// Default retention class for this memory entry kind.
    #[must_use]
    pub const fn retention(self) -> CompactionRetention {
        match self {
            Self::TopicAgentsMd | Self::Summary | Self::ArchiveReference => {
                CompactionRetention::Pinned
            }
            Self::SystemContext
            | Self::UserTask
            | Self::RuntimeContext
            | Self::SkillContext
            | Self::ApprovalReplay
            | Self::InfraStatus => CompactionRetention::ProtectedLive,
            Self::ToolResult => CompactionRetention::PrunableArtifact,
            Self::Legacy
            | Self::UserTurn
            | Self::AssistantResponse
            | Self::AssistantReasoning
            | Self::AssistantToolCall => CompactionRetention::CompactableHistory,
        }
    }
}

/// Trigger point for a compaction pipeline invocation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompactionTrigger {
    /// Compaction check before the first model request of a run.
    PreRun,
    /// Compaction check before a later loop iteration.
    PreIteration,
    /// Explicit manual compaction requested by the operator or transport.
    Manual,
}

/// Static policy knobs for the compaction subsystem.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompactionPolicy {
    /// Legacy token threshold kept for the Stage 1 transition period.
    pub legacy_compact_threshold: usize,
}

impl Default for CompactionPolicy {
    fn default() -> Self {
        Self {
            legacy_compact_threshold: AGENT_COMPACT_THRESHOLD,
        }
    }
}

/// Immutable request payload describing a compaction checkpoint.
#[derive(Debug, Clone)]
pub struct CompactionRequest<'a> {
    /// Why the pipeline was invoked.
    pub trigger: CompactionTrigger,
    /// User-visible task text.
    pub task: &'a str,
    /// Current fully rendered system prompt.
    pub system_prompt: &'a str,
    /// Tool definitions exposed to the model.
    pub tools: &'a [ToolDefinition],
    /// Active model name for the main agent request.
    pub model_name: &'a str,
    /// Whether the current execution is a sub-agent.
    pub is_sub_agent: bool,
}

impl<'a> CompactionRequest<'a> {
    /// Build a request for a compaction checkpoint.
    #[must_use]
    pub const fn new(
        trigger: CompactionTrigger,
        task: &'a str,
        system_prompt: &'a str,
        tools: &'a [ToolDefinition],
        model_name: &'a str,
        is_sub_agent: bool,
    ) -> Self {
        Self {
            trigger,
            task,
            system_prompt,
            tools,
            model_name,
            is_sub_agent,
        }
    }
}

/// Observable result of a compaction checkpoint.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompactionOutcome {
    /// Trigger that produced this outcome.
    pub trigger: CompactionTrigger,
    /// Whether the pipeline mutated hot memory.
    pub applied: bool,
    /// Token count before the pipeline ran.
    pub token_count_before: usize,
    /// Token count after the pipeline ran.
    pub token_count_after: usize,
}

impl CompactionOutcome {
    /// Build a no-op outcome.
    #[must_use]
    pub const fn noop(trigger: CompactionTrigger, token_count: usize) -> Self {
        Self {
            trigger,
            applied: false,
            token_count_before: token_count,
            token_count_after: token_count,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{AgentMessageKind, CompactionRetention};

    #[test]
    fn topic_agents_md_is_pinned() {
        assert_eq!(
            AgentMessageKind::TopicAgentsMd.retention(),
            CompactionRetention::Pinned
        );
    }

    #[test]
    fn tool_results_are_prunable() {
        assert_eq!(
            AgentMessageKind::ToolResult.retention(),
            CompactionRetention::PrunableArtifact
        );
    }

    #[test]
    fn live_context_entries_are_protected() {
        assert_eq!(
            AgentMessageKind::UserTask.retention(),
            CompactionRetention::ProtectedLive
        );
        assert_eq!(
            AgentMessageKind::SkillContext.retention(),
            CompactionRetention::ProtectedLive
        );
    }
}
