//! Shared types for Agent Mode context compaction.

use crate::llm::ToolDefinition;
use serde::{Deserialize, Serialize};

const WIKI_MEMORY_LOOKUP_TOOLS: &[&str] =
    &["wiki_memory_list", "wiki_memory_read", "wiki_memory_search"];

/// Return whether scoped durable wiki lookup tools are actually exposed to this run.
#[must_use]
pub fn wiki_memory_lookup_available(tools: &[ToolDefinition]) -> bool {
    WIKI_MEMORY_LOOKUP_TOOLS
        .iter()
        .all(|required| tools.iter().any(|tool| tool.name == *required))
}

/// Stable semantic kind for an entry stored in hot agent memory.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum AgentMessageKind {
    /// Generic system context injected into the run.
    SystemContext,
    /// Topic-scoped pinned `AGENTS.md` content.
    TopicAgentsMd,
    /// Primary user task for the current run.
    UserTask,
    /// Additional user context injected while a run is active.
    RuntimeContext,
    /// Generic user turn without stronger typing metadata.
    UserTurn,
    /// Final or intermediate assistant answer.
    AssistantResponse,
    /// Assistant answer that contains hidden reasoning content.
    AssistantReasoning,
    /// Assistant message that requests tool execution.
    AssistantToolCall,
    /// Assistant draft generated in a turn that was not delivered to the user.
    UndeliveredAssistantDraft,
    /// Raw tool result retained in hot memory.
    ToolResult,
    /// System status about topic-scoped infra.
    InfraStatus,
    /// Summary generated by compaction.
    Summary,
}

/// Retention class used by future compaction policies.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum CompactionRetention {
    /// Must stay raw in hot context and never be compacted.
    Pinned,
    /// Keep raw while the work is still active.
    ProtectedLive,
    /// Large artifacts that should be pruned or externalized before summary.
    PrunableArtifact,
    /// Historical conversation content eligible for summary compaction.
    CompactableHistory,
}

impl AgentMessageKind {
    /// Default retention class for this memory entry kind.
    #[must_use]
    pub const fn retention(self) -> CompactionRetention {
        match self {
            Self::TopicAgentsMd | Self::Summary => CompactionRetention::Pinned,
            Self::SystemContext | Self::UserTask | Self::RuntimeContext | Self::InfraStatus => {
                CompactionRetention::ProtectedLive
            }
            Self::ToolResult => CompactionRetention::PrunableArtifact,
            Self::UserTurn
            | Self::AssistantResponse
            | Self::AssistantReasoning
            | Self::AssistantToolCall
            | Self::UndeliveredAssistantDraft => CompactionRetention::CompactableHistory,
        }
    }
}

/// Resolve the retention class for a message, allowing tool-aware overrides.
#[must_use]
pub fn resolve_retention(kind: AgentMessageKind, tool_name: Option<&str>) -> CompactionRetention {
    match kind {
        AgentMessageKind::ToolResult if is_summary_preferred_tool(tool_name) => {
            CompactionRetention::CompactableHistory
        }
        _ => kind.retention(),
    }
}

fn is_summary_preferred_tool(tool_name: Option<&str>) -> bool {
    matches!(tool_name, Some("wait_sub_agents"))
}

/// Trigger point for a compaction pipeline invocation.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum CompactionTrigger {
    /// Compaction check before the first model request of a run.
    PreRun,
    /// Compaction check before a later loop iteration.
    PreIteration,
    /// Explicit manual compaction requested by the operator or transport.
    Manual,
}

/// Why runtime/session-level compaction is requested.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum CompactionReason {
    /// Normal pre-turn/pre-sampling budget management.
    PreTurn,
    /// Runtime continuation within a turn needs a smaller context.
    MidTurn,
    /// Explicit operator or transport request.
    Manual,
    /// Provider reported or strongly implied context overflow.
    ContextLimit,
    /// Route/failover selected a model with a smaller context window.
    ModelDownshift,
}

/// Where compaction happens in the runtime flow.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum CompactionPhase {
    /// Before the next provider sampling request.
    PreSampling,
    /// While a turn is still in progress and needs follow-up sampling.
    MidTurn,
    /// Explicit manual compact operation.
    Manual,
    /// During model route/failover switching.
    ModelSwitch,
}

/// Backend that generated a compact handoff summary.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum CompactionBackend {
    /// Provider-agnostic ordinary LLM text request.
    LocalLlmSummary,
}

impl CompactionBackend {
    /// Stable label for progress/events/summary metadata.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::LocalLlmSummary => "local_llm_summary",
        }
    }
}

/// Static policy knobs for the compaction subsystem.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompactionPolicy {
    /// Percent of the window where warning-level telemetry should start.
    pub warning_threshold_percent: u8,
    /// Percent of the window where compaction becomes desirable.
    pub compact_threshold_percent: u8,
    /// Percent of the window treated as an over-limit safety cap.
    pub over_limit_threshold_percent: u8,
    /// Reserved buffer kept free beyond the input request.
    pub hard_reserve_tokens: usize,
}

impl Default for CompactionPolicy {
    fn default() -> Self {
        Self {
            warning_threshold_percent: 65,
            compact_threshold_percent: 85,
            over_limit_threshold_percent: 95,
            hard_reserve_tokens: 8_192,
        }
    }
}

/// Agent/session scope metadata used for archive and payload keys.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompactionScope {
    /// Stable context key for topic/thread/session scope.
    pub context_key: String,
    /// Stable flow identifier within the context.
    pub flow_id: String,
}

impl Default for CompactionScope {
    fn default() -> Self {
        Self {
            context_key: "unknown-context".to_string(),
            flow_id: "hot-memory".to_string(),
        }
    }
}

/// Immutable request payload describing a compaction checkpoint.
#[derive(Debug, Clone)]
pub struct CompactionRequest<'a> {
    /// Why the pipeline was invoked.
    pub trigger: CompactionTrigger,
    /// User-visible task text.
    pub task: &'a str,
    /// Current fully rendered system prompt.
    pub system_prompt: &'a str,
    /// Tool definitions exposed to the model.
    pub tools: &'a [ToolDefinition],
    /// Active model name for the main agent request.
    pub model_name: &'a str,
    /// Configured response token cap for the active model. This is not pre-reserved from input.
    pub model_max_output_tokens: u32,
    /// Whether the current execution is a sub-agent.
    pub is_sub_agent: bool,
}

impl<'a> CompactionRequest<'a> {
    /// Build a request for a compaction checkpoint.
    #[must_use]
    pub const fn new(
        trigger: CompactionTrigger,
        task: &'a str,
        system_prompt: &'a str,
        tools: &'a [ToolDefinition],
        model_name: &'a str,
        model_max_output_tokens: u32,
        is_sub_agent: bool,
    ) -> Self {
        Self {
            trigger,
            task,
            system_prompt,
            tools,
            model_name,
            model_max_output_tokens,
            is_sub_agent,
        }
    }
}

/// Health state derived from the estimated full request budget.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum BudgetState {
    /// Plenty of room remains in the request budget.
    Healthy,
    /// Context is growing and should be surfaced to telemetry.
    Warning,
    /// History compaction should run before the next model call.
    ShouldCompact,
    /// The projected request would exceed the configured window.
    OverLimit,
}

impl BudgetState {
    /// Returns true when the checkpoint should emit warning-level telemetry.
    #[must_use]
    pub const fn requires_warn_telemetry(self) -> bool {
        matches!(self, Self::ShouldCompact | Self::OverLimit)
    }
}

/// Token accounting grouped by hot-memory retention class.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HotMemoryBudget {
    /// Total estimated tokens represented by the current hot memory.
    pub total_tokens: usize,
    /// Total messages represented in hot memory.
    pub total_messages: usize,
    /// Tokens belonging to pinned messages.
    pub pinned_tokens: usize,
    /// Tokens belonging to protected live messages.
    pub protected_live_tokens: usize,
    /// Tokens belonging to prunable artifact messages.
    pub prunable_artifact_tokens: usize,
    /// Tokens belonging to compactable history messages.
    pub compactable_history_tokens: usize,
    /// Tokens specifically attributed to runtime context messages.
    pub runtime_context_tokens: usize,
}

/// Full request budget estimate for a compaction checkpoint.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BudgetEstimate {
    /// Configured effective context window for Agent Mode.
    pub context_window_tokens: usize,
    /// Estimated token count of the rendered system prompt.
    pub system_prompt_tokens: usize,
    /// Estimated token count of serialized tool schemas.
    pub tool_schema_tokens: usize,
    /// Estimated token count of the active hot memory.
    pub hot_memory: HotMemoryBudget,
    /// Output tokens pre-reserved from the input window. Kept for API compatibility; currently zero.
    pub reserved_output_tokens: usize,
    /// Additional hard safety buffer kept free.
    pub hard_reserve_tokens: usize,
    /// Estimated input-side request size before model completion tokens.
    pub total_input_tokens: usize,
    /// Estimated input-side request size including the hard reserve.
    pub projected_total_tokens: usize,
    /// Remaining headroom in the configured context window.
    pub headroom_tokens: usize,
    /// Warning threshold derived from policy and window size.
    pub warning_threshold_tokens: usize,
    /// Compact threshold derived from policy and window size.
    pub compact_threshold_tokens: usize,
    /// Over-limit threshold derived from policy and window size.
    pub over_limit_threshold_tokens: usize,
    /// High-level budget state.
    pub state: BudgetState,
}

#[cfg(test)]
mod tests {
    use super::{
        AgentMessageKind, BudgetState, CompactionPolicy, CompactionRetention, resolve_retention,
        wiki_memory_lookup_available,
    };
    use crate::llm::ToolDefinition;

    fn tool(name: &str) -> ToolDefinition {
        ToolDefinition {
            name: name.to_string(),
            description: "test tool".to_string(),
            parameters: serde_json::json!({"type": "object"}),
        }
    }

    #[test]
    fn topic_agents_md_is_pinned() {
        assert_eq!(
            AgentMessageKind::TopicAgentsMd.retention(),
            CompactionRetention::Pinned
        );
    }

    #[test]
    fn tool_results_are_prunable() {
        assert_eq!(
            AgentMessageKind::ToolResult.retention(),
            CompactionRetention::PrunableArtifact
        );
    }

    #[test]
    fn sub_agent_wait_results_are_summary_preferred() {
        assert_eq!(
            resolve_retention(AgentMessageKind::ToolResult, Some("wait_sub_agents")),
            CompactionRetention::CompactableHistory
        );
        assert_eq!(
            resolve_retention(AgentMessageKind::ToolResult, Some("ssh_exec")),
            CompactionRetention::PrunableArtifact
        );
    }

    #[test]
    fn wiki_memory_lookup_requires_actual_lookup_tool_definitions() {
        let tools = vec![
            tool("wiki_memory_list"),
            tool("wiki_memory_read"),
            tool("wiki_memory_search"),
            tool("wiki_memory_delete"),
        ];
        assert!(wiki_memory_lookup_available(&tools));

        let missing_search = vec![tool("wiki_memory_list"), tool("wiki_memory_read")];
        assert!(!wiki_memory_lookup_available(&missing_search));

        let no_wiki = vec![tool("read_file")];
        assert!(!wiki_memory_lookup_available(&no_wiki));
    }

    #[test]
    fn live_context_entries_are_protected() {
        assert_eq!(
            AgentMessageKind::UserTask.retention(),
            CompactionRetention::ProtectedLive
        );
        assert_eq!(
            AgentMessageKind::RuntimeContext.retention(),
            CompactionRetention::ProtectedLive
        );
    }

    #[test]
    fn default_policy_keeps_thresholds_ordered() {
        let policy = CompactionPolicy::default();
        assert!(policy.warning_threshold_percent < policy.compact_threshold_percent);
        assert!(policy.compact_threshold_percent < policy.over_limit_threshold_percent);
        assert!(policy.hard_reserve_tokens > 0);
    }

    #[test]
    fn budget_state_warn_telemetry_starts_at_compaction() {
        assert!(!BudgetState::Healthy.requires_warn_telemetry());
        assert!(!BudgetState::Warning.requires_warn_telemetry());
        assert!(BudgetState::ShouldCompact.requires_warn_telemetry());
        assert!(BudgetState::OverLimit.requires_warn_telemetry());
    }
}
