//! Scripted LLM providers used in E2E tests.

use async_trait::async_trait;
use oxide_agent_core::llm::{ChatResponse, ChatWithToolsRequest, LlmError, LlmProvider, Message};
use std::collections::{BTreeSet, VecDeque};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Arc;
use std::sync::Mutex as StdMutex;
use tokio::sync::{Mutex, Notify};

#[derive(Debug, Clone)]
pub struct RecordedToolRequest {
    pub system_prompt: String,
    pub messages: Vec<Message>,
}

/// Scripted ZAI provider that returns pre-programmed responses in sequence.
/// Logs each model_id call for verification.
#[derive(Clone)]
pub struct SequencedZaiProvider {
    responses: Arc<Mutex<VecDeque<ChatResponse>>>,
    model_log: Arc<Mutex<Vec<String>>>,
    request_log: Arc<Mutex<Vec<RecordedToolRequest>>>,
    call_count: Arc<AtomicUsize>,
    blocked_calls: Arc<StdMutex<BTreeSet<usize>>>,
    released_calls: Arc<StdMutex<BTreeSet<usize>>>,
    notify: Arc<Notify>,
}

impl SequencedZaiProvider {
    pub fn new(responses: Vec<ChatResponse>) -> Self {
        Self {
            responses: Arc::new(Mutex::new(VecDeque::from(responses))),
            model_log: Arc::new(Mutex::new(Vec::new())),
            request_log: Arc::new(Mutex::new(Vec::new())),
            call_count: Arc::new(AtomicUsize::new(0)),
            blocked_calls: Arc::new(StdMutex::new(BTreeSet::new())),
            released_calls: Arc::new(StdMutex::new(BTreeSet::new())),
            notify: Arc::new(Notify::new()),
        }
    }

    pub fn with_blocked_calls<I>(self, blocked_calls: I) -> Self
    where
        I: IntoIterator<Item = usize>,
    {
        let provider = self;
        *provider
            .blocked_calls
            .lock()
            .expect("blocked calls mutex poisoned") = BTreeSet::from_iter(blocked_calls);
        provider
    }

    pub async fn model_log(&self) -> Vec<String> {
        self.model_log.lock().await.clone()
    }

    pub async fn request_log(&self) -> Vec<RecordedToolRequest> {
        self.request_log.lock().await.clone()
    }

    pub fn release_call(&self, call_index: usize) {
        self.released_calls
            .lock()
            .expect("released calls mutex poisoned")
            .insert(call_index);
        self.notify.notify_waiters();
    }

    async fn wait_if_blocked(&self, call_index: usize) {
        loop {
            let is_blocked = self
                .blocked_calls
                .lock()
                .expect("blocked calls mutex poisoned")
                .contains(&call_index);
            if !is_blocked {
                return;
            }

            if self
                .released_calls
                .lock()
                .expect("released calls mutex poisoned")
                .contains(&call_index)
            {
                return;
            }

            self.notify.notified().await;
        }
    }
}

#[async_trait]
impl LlmProvider for SequencedZaiProvider {
    async fn complete_internal_text(
        &self,
        _system_prompt: &str,
        _history: &[Message],
        _user_message: &str,
        model_id: &str,
        _max_tokens: u32,
    ) -> Result<String, LlmError> {
        Ok(format!(
            "Runtime compaction summary generated by {model_id}."
        ))
    }

    async fn chat_with_tools<'a>(
        &self,
        request: ChatWithToolsRequest<'a>,
    ) -> Result<ChatResponse, LlmError> {
        let call_index = self.call_count.fetch_add(1, Ordering::SeqCst) + 1;
        self.model_log
            .lock()
            .await
            .push(request.model_id.to_string());
        self.request_log.lock().await.push(RecordedToolRequest {
            system_prompt: request.system_prompt.to_string(),
            messages: request.messages.to_vec(),
        });

        self.wait_if_blocked(call_index).await;

        self.responses
            .lock()
            .await
            .pop_front()
            .ok_or_else(|| LlmError::ApiError("No scripted ZAI response available".to_string()))
    }

    async fn transcribe_audio(
        &self,
        _audio_bytes: Vec<u8>,
        _mime_type: &str,
        _model_id: &str,
    ) -> Result<String, LlmError> {
        Err(LlmError::Unknown("transcribe not implemented".to_string()))
    }

    async fn analyze_image(
        &self,
        _image_bytes: Vec<u8>,
        _text_prompt: &str,
        _system_prompt: &str,
        _model_id: &str,
    ) -> Result<String, LlmError> {
        Err(LlmError::Unknown(
            "analyze_image not implemented".to_string(),
        ))
    }
}
