use_default_settings:
  engines:
    keep_only:
      - brave
      - bing
      - qwant
      - mojeek
      - yandex

general:
  debug: false
  instance_name: "oxide-searxng"

search:
  safe_search: 0
  autocomplete: ""
  favicon_resolver: ""
  default_lang: ""
  languages:
    - all
    - ru
    - uk
    - en
  formats:
    - json
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120

server:
  base_url: false
  secret_key: "change-this-searxng-secret"
  limiter: false
  public_instance: false
  image_proxy: false
  method: "POST"

engines:
  - name: brave
    disabled: false
  - name: bing
    disabled: false
  - name: qwant
    disabled: false
  - name: mojeek
    disabled: false
  - name: yandex
    disabled: false

outgoing:
  request_timeout: 4.0
  retries: 0
  pool_maxsize: 8
  pool_connections: 32
  keepalive_expiry: 5.0
  enable_http2: true
  useragent_suffix: "oxide-agent"
