use super::config::WikiMemoryConfig;
use super::store::WikiStore;
use crate::storage::StorageError;
use serde::{Deserialize, Serialize};
use std::collections::HashSet;

/// Limits for validating one wiki patch set.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WikiPatchValidatorConfig {
    /// Maximum operations in one patch set.
    pub max_operations: usize,
    /// Maximum changed durable pages in one patch set.
    pub max_changed_pages: usize,
    /// Maximum total patch bytes in one patch set.
    pub max_total_patch_bytes: usize,
    /// Page size limits.
    pub memory: WikiMemoryConfig,
}

impl Default for WikiPatchValidatorConfig {
    fn default() -> Self {
        Self {
            max_operations: 12,
            max_changed_pages: 6,
            max_total_patch_bytes: 96 * 1024,
            memory: WikiMemoryConfig::default(),
        }
    }
}

/// Structured patch set generated by a future planner and validated by runtime.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WikiPatchSet {
    /// Human-readable reason for this patch cycle.
    pub reason: String,
    /// Compact source refs grounding the update.
    pub source_refs: Vec<String>,
    /// Page-scoped operations.
    pub operations: Vec<WikiPatchOperation>,
}

/// One requested wiki page operation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum WikiPatchOperation {
    /// Upsert an existing or new durable page.
    UpsertPage {
        /// Scope-relative wiki path such as `contexts/{context_id}/procedures.md`.
        path: String,
        /// Optional expected content hash.
        expected_hash: Option<String>,
        /// Full Markdown page content.
        content: String,
    },
    /// Create a new durable page.
    CreatePage {
        /// Scope-relative wiki path such as `contexts/{context_id}/pages/deploy-runbook.md`.
        path: String,
        /// Full Markdown page content.
        content: String,
    },
    /// Create a low-confidence inbox item.
    CreateInboxItem {
        /// Scope-relative inbox path.
        path: String,
        /// Full Markdown page content.
        content: String,
    },
}

/// Runtime-validated patch operation with a deterministic storage key.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ValidatedWikiPatchOperation {
    /// Deterministic storage key.
    pub key: String,
    /// Full Markdown page content.
    pub content: String,
    /// Optional expected hash from planner.
    pub expected_hash: Option<String>,
    /// Whether this operation writes an inbox item.
    pub inbox: bool,
}

/// Runtime-validated patch set.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ValidatedWikiPatch {
    /// Human-readable reason for this patch cycle.
    pub reason: String,
    /// Compact source refs grounding the update.
    pub source_refs: Vec<String>,
    /// Validated operations.
    pub operations: Vec<ValidatedWikiPatchOperation>,
}

/// Validator that constrains LLM-supplied wiki patches to scoped Markdown keys.
pub struct WikiPatchValidator {
    config: WikiPatchValidatorConfig,
}

impl WikiPatchValidator {
    /// Create a validator with runtime limits.
    #[must_use]
    pub fn new(config: WikiPatchValidatorConfig) -> Self {
        Self { config }
    }

    /// Validate and resolve deterministic object keys for a patch set.
    pub fn validate(
        &self,
        store: &WikiStore,
        context_id: &str,
        patch: WikiPatchSet,
    ) -> Result<ValidatedWikiPatch, StorageError> {
        if patch.operations.is_empty() {
            return Err(StorageError::InvalidInput(
                "wiki patch must contain at least one operation".to_string(),
            ));
        }
        if patch.operations.len() > self.config.max_operations {
            return Err(StorageError::InvalidInput(
                "wiki patch has too many operations".to_string(),
            ));
        }
        if patch.source_refs.is_empty() {
            return Err(StorageError::InvalidInput(
                "wiki patch must include source refs".to_string(),
            ));
        }

        let mut total_bytes = 0;
        let mut changed_pages = HashSet::new();
        let mut operations = Vec::with_capacity(patch.operations.len());

        for operation in patch.operations {
            let validated = self.validate_operation(store, context_id, operation)?;
            total_bytes += validated.content.len();
            if total_bytes > self.config.max_total_patch_bytes {
                return Err(StorageError::InvalidInput(
                    "wiki patch exceeds total byte limit".to_string(),
                ));
            }
            changed_pages.insert(validated.key.clone());
            if changed_pages.len() > self.config.max_changed_pages {
                return Err(StorageError::InvalidInput(
                    "wiki patch changes too many pages".to_string(),
                ));
            }
            operations.push(validated);
        }

        Ok(ValidatedWikiPatch {
            reason: patch.reason.trim().to_string(),
            source_refs: patch.source_refs,
            operations,
        })
    }

    fn validate_operation(
        &self,
        store: &WikiStore,
        context_id: &str,
        operation: WikiPatchOperation,
    ) -> Result<ValidatedWikiPatchOperation, StorageError> {
        match operation {
            WikiPatchOperation::UpsertPage {
                path,
                expected_hash,
                content,
            } => self.validate_page_op(store, context_id, &path, expected_hash, content, false),
            WikiPatchOperation::CreatePage { path, content } => {
                self.validate_page_op(store, context_id, &path, None, content, false)
            }
            WikiPatchOperation::CreateInboxItem { path, content } => {
                self.validate_page_op(store, context_id, &path, None, content, true)
            }
        }
    }

    fn validate_page_op(
        &self,
        store: &WikiStore,
        context_id: &str,
        path: &str,
        expected_hash: Option<String>,
        content: String,
        inbox: bool,
    ) -> Result<ValidatedWikiPatchOperation, StorageError> {
        validate_content(&content, inbox)?;
        let key = resolve_patch_path(store, context_id, path, inbox)?;
        let limit = if inbox {
            self.config.memory.inbox_item_max_bytes
        } else if path.ends_with("index.md") {
            self.config.memory.index_max_bytes
        } else if path.ends_with("log.md") {
            self.config.memory.log_max_bytes
        } else {
            self.config.memory.normal_page_max_bytes
        };
        if content.len() > limit {
            return Err(StorageError::InvalidInput(
                "wiki patch page exceeds size limit".to_string(),
            ));
        }
        if !inbox && (path.ends_with("index.md") || path.ends_with("log.md")) {
            return Err(StorageError::InvalidInput(
                "wiki patch cannot directly edit protected index.md or log.md".to_string(),
            ));
        }
        if !inbox && !content_has_required_frontmatter(&content) {
            return Err(StorageError::InvalidInput(
                "wiki page must include required frontmatter".to_string(),
            ));
        }

        Ok(ValidatedWikiPatchOperation {
            key,
            content,
            expected_hash,
            inbox,
        })
    }
}

fn resolve_patch_path(
    store: &WikiStore,
    context_id: &str,
    path: &str,
    inbox: bool,
) -> Result<String, StorageError> {
    validate_path_string(path)?;
    let context_prefix = format!("contexts/{context_id}/");
    if let Some(file) = path.strip_prefix("global/") {
        return match file {
            "user.md" | "preferences.md" => store.global_file_key(file),
            _ => Err(StorageError::InvalidInput(
                "wiki patch global path is not allowlisted".to_string(),
            )),
        };
    }

    let Some(relative) = path.strip_prefix(&context_prefix) else {
        return Err(StorageError::InvalidInput(
            "wiki patch path is outside context scope".to_string(),
        ));
    };

    if inbox {
        let slug = relative
            .strip_prefix("inbox/")
            .and_then(|value| value.strip_suffix(".md"))
            .ok_or_else(|| {
                StorageError::InvalidInput("wiki inbox path must target inbox/*.md".to_string())
            })?;
        return store.context_inbox_key(context_id, slug);
    }

    match relative {
        "overview.md" | "decisions.md" | "constraints.md" | "procedures.md"
        | "open-questions.md" => store.context_file_key(context_id, relative),
        _ => {
            let slug = relative
                .strip_prefix("pages/")
                .and_then(|value| value.strip_suffix(".md"))
                .ok_or_else(|| {
                    StorageError::InvalidInput("wiki page path is not allowlisted".to_string())
                })?;
            store.context_page_key(context_id, slug)
        }
    }
}

fn validate_path_string(path: &str) -> Result<(), StorageError> {
    if path.is_empty()
        || path.starts_with('/')
        || path.contains("..")
        || path.contains('\\')
        || path.contains("://")
        || path.chars().any(char::is_control)
    {
        return Err(StorageError::InvalidInput(
            "wiki patch path contains unsafe characters".to_string(),
        ));
    }
    if !path.ends_with(".md") {
        return Err(StorageError::InvalidInput(
            "wiki patch path must target Markdown".to_string(),
        ));
    }
    Ok(())
}

fn validate_content(content: &str, inbox: bool) -> Result<(), StorageError> {
    if content.trim().is_empty() {
        return Err(StorageError::InvalidInput(
            "wiki patch content is empty".to_string(),
        ));
    }
    let lowered = content.to_ascii_lowercase();
    if lowered.contains("api_key")
        || lowered.contains("secret_access_key")
        || lowered.contains("begin openssh private key")
        || lowered.contains("authorization: bearer")
    {
        return Err(StorageError::InvalidInput(
            "wiki patch content appears to contain a secret".to_string(),
        ));
    }
    if !inbox && looks_like_raw_transcript(content) {
        return Err(StorageError::InvalidInput(
            "wiki patch content looks like a raw transcript dump".to_string(),
        ));
    }
    Ok(())
}

fn looks_like_raw_transcript(content: &str) -> bool {
    let transcript_lines = content
        .lines()
        .filter(|line| {
            let line = line.trim_start().to_ascii_lowercase();
            line.starts_with("user:")
                || line.starts_with("assistant:")
                || line.starts_with("tool:")
                || line.contains("tool_call_id")
        })
        .count();
    transcript_lines >= 5
}

fn content_has_required_frontmatter(content: &str) -> bool {
    if !content.starts_with("---\n") {
        return false;
    }
    let Some(end) = content[4..].find("\n---") else {
        return false;
    };
    let frontmatter = &content[4..4 + end];
    [
        "title:",
        "type:",
        "updated_at:",
        "confidence:",
        "tags:",
        "sources:",
    ]
    .iter()
    .all(|field| {
        frontmatter
            .lines()
            .any(|line| line.trim_start().starts_with(field))
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agent::wiki_memory::WikiObjectBackend;
    use async_trait::async_trait;
    use std::sync::Arc;

    struct NoopBackend;

    #[async_trait]
    impl WikiObjectBackend for NoopBackend {
        async fn get_text(&self, _key: &str) -> Result<Option<String>, StorageError> {
            Ok(None)
        }

        async fn put_text(&self, _key: &str, _content: &str) -> Result<(), StorageError> {
            Ok(())
        }

        async fn delete_text(&self, _key: &str) -> Result<(), StorageError> {
            Ok(())
        }
    }

    fn page(content: &str) -> String {
        format!(
            "---\ntitle: Test\ntype: note\nupdated_at: 2026-05-19T00:00:00Z\nconfidence: high\ntags: []\nsources:\n  - run:test\n---\n\n# Test\n\n{content}"
        )
    }

    #[test]
    fn validator_accepts_scoped_context_page() {
        let store = WikiStore::new(Arc::new(NoopBackend), "prod");
        let patch = WikiPatchSet {
            reason: "remember runbook".to_string(),
            source_refs: vec!["run:test".to_string()],
            operations: vec![WikiPatchOperation::UpsertPage {
                path: "contexts/ctx-12345678/procedures.md".to_string(),
                expected_hash: None,
                content: page("Procedure"),
            }],
        };

        let validated = WikiPatchValidator::new(WikiPatchValidatorConfig::default())
            .validate(&store, "ctx-12345678", patch)
            .expect("patch should validate");

        assert_eq!(
            validated.operations[0].key,
            "prod/wiki/v1/contexts/ctx-12345678/procedures.md"
        );
    }

    #[test]
    fn validator_rejects_path_outside_context_scope() {
        let store = WikiStore::new(Arc::new(NoopBackend), "prod");
        let patch = WikiPatchSet {
            reason: "bad".to_string(),
            source_refs: vec!["run:test".to_string()],
            operations: vec![WikiPatchOperation::UpsertPage {
                path: "contexts/other/procedures.md".to_string(),
                expected_hash: None,
                content: page("Procedure"),
            }],
        };

        let result = WikiPatchValidator::new(WikiPatchValidatorConfig::default()).validate(
            &store,
            "ctx-12345678",
            patch,
        );

        assert!(matches!(result, Err(StorageError::InvalidInput(_))));
    }

    #[test]
    fn validator_rejects_missing_frontmatter() {
        let store = WikiStore::new(Arc::new(NoopBackend), "prod");
        let patch = WikiPatchSet {
            reason: "bad".to_string(),
            source_refs: vec!["run:test".to_string()],
            operations: vec![WikiPatchOperation::UpsertPage {
                path: "contexts/ctx-12345678/overview.md".to_string(),
                expected_hash: None,
                content: "# Raw".to_string(),
            }],
        };

        let result = WikiPatchValidator::new(WikiPatchValidatorConfig::default()).validate(
            &store,
            "ctx-12345678",
            patch,
        );

        assert!(matches!(result, Err(StorageError::InvalidInput(_))));
    }

    #[test]
    fn validator_rejects_protected_index_edits() {
        let store = WikiStore::new(Arc::new(NoopBackend), "prod");
        let patch = WikiPatchSet {
            reason: "bad".to_string(),
            source_refs: vec!["run:test".to_string()],
            operations: vec![WikiPatchOperation::UpsertPage {
                path: "contexts/ctx-12345678/index.md".to_string(),
                expected_hash: None,
                content: page("Index"),
            }],
        };

        let result = WikiPatchValidator::new(WikiPatchValidatorConfig::default()).validate(
            &store,
            "ctx-12345678",
            patch,
        );

        assert!(matches!(result, Err(StorageError::InvalidInput(_))));
    }

    #[test]
    fn validator_rejects_secret_like_content() {
        let store = WikiStore::new(Arc::new(NoopBackend), "prod");
        let patch = WikiPatchSet {
            reason: "bad".to_string(),
            source_refs: vec!["run:test".to_string()],
            operations: vec![WikiPatchOperation::CreateInboxItem {
                path: "contexts/ctx-12345678/inbox/low-confidence.md".to_string(),
                content: "api_key: secret".to_string(),
            }],
        };

        let result = WikiPatchValidator::new(WikiPatchValidatorConfig::default()).validate(
            &store,
            "ctx-12345678",
            patch,
        );

        assert!(matches!(result, Err(StorageError::InvalidInput(_))));
    }
}
