profile = "search-only"
cargo_features = ["profile-search-only"]

[modules]
"transport/telegram" = { enabled = true }
"storage/sqlx" = { enabled = true }
"llm-provider/opencode-go" = { enabled = true }
"tool/webfetch-md" = { enabled = true }
"tool/tavily" = { enabled = true }
"tool/duckduckgo" = { enabled = true }
"tool/brave-search" = { enabled = true }
"tool/searxng" = { enabled = true }
